# Copyright (c) 2025 Roman Barinov <rbarinov@gmail.com>
# Licensed under the FSL-1.1-NC.
#
# Gemfile for Tiflis Code iOS Fastlane setup

source "https://rubygems.org"

gem "fastlane", "~> 2.225"

# Plugins
# gem "fastlane-plugin-..."
